# Artificial Neural Network

### Importing the libraries

In [170]:
import numpy as np
import pandas as pd
import tensorflow as tf

## Part 1 - Data Preprocessing

### Importing the dataset

In [171]:
data = pd.read_csv(r'Churn_Modelling.csv')

X = data.iloc[:,3:-1].values
y = data.iloc[:,-1].values
data.head(2)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   

   Tenure   Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2      0.00              1          1               1   
1       1  83807.86              1          0               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0

In [172]:
print(X)
print(X.shape)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
(10000, 10)


In [173]:
print(y)
print(y.shape)

[1 0 1 ... 1 1 0]
(10000,)


In [174]:
data.isna().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

There is no Missing Values in the dataset

### Encoding categorical data

Label Encoding the "Gender" column

In [175]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

One Hot Encoding the "Geography" column

In [176]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = ct.fit_transform(X)

In [177]:
print(X[0])

[1.0 0.0 0.0 619 0 42 2 0.0 1 1 1 101348.88]


### Splitting the dataset into the Training set and Test set

In [178]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

### Feature Scaling

In [179]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [180]:
X_train[0]

array([ 0.99750312, -0.57273139, -0.58004459,  1.57651993,  0.90704943,
       -0.27603201, -1.37694145, -1.22214571,  0.81988483,  0.64784127,
        0.97238125,  0.8599091 ])

## Part 2 - Building the ANN

### Initializing the ANN

In [181]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [182]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the second hidden layer

In [183]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the output layer

In [184]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [185]:
ann.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

### Training the ANN on the Training set

In [187]:
ann.fit(X_train, y_train, batch_size = 20, epochs = 100)

Epoch 1/100
8000/8000 [==============================] - 1s 148us/sample - loss: 0.3374 - acc: 0.8629
Epoch 2/100
8000/8000 [==============================] - 1s 128us/sample - loss: 0.3363 - acc: 0.8636
Epoch 3/100
8000/8000 [==============================] - 1s 121us/sample - loss: 0.3363 - acc: 0.8621
Epoch 4/100
8000/8000 [==============================] - 1s 116us/sample - loss: 0.3364 - acc: 0.8619
Epoch 5/100
8000/8000 [==============================] - 1s 125us/sample - loss: 0.3360 - acc: 0.8651
Epoch 6/100
8000/8000 [==============================] - 1s 140us/sample - loss: 0.3355 - acc: 0.8618
Epoch 7/100
8000/8000 [==============================] - 1s 123us/sample - loss: 0.3357 - acc: 0.8610
Epoch 8/100
8000/8000 [==============================] - 1s 129us/sample - loss: 0.3355 - acc: 0.8626
Epoch 9/100
8000/8000 [==============================] - 1s 141us/sample - loss: 0.3354 - acc: 0.8625
Epoch 10/100
8000/8000 [==============================] - 1s 114us/sample - loss: 

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

In [188]:
X_test_1 = np.array([[600, 'France', 'Female', 40, 3, 60000, 2, 1, 1, 50000]])


X_test_1[:, 2] = le.transform(X_test_1[:, 2]) ; X_test_1 = ct.transform(X_test_1); X_test_1 = sc.transform(X_test_1)

if ann.predict(X_test_1) > 0.5 : 
    print('Customer will leave')
else : 
    print('Customer stays in the bank')

Customer stays in the bank


.....................................................................................................................................................

Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [189]:
y_pred = ann.predict(X_test)
y_pred = np.where(y_pred > 0.5, 1,0)

### Making the Confusion Matrix

In [190]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)

array([[1528,   61],
       [ 225,  186]], dtype=int64)

In [191]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.857